### ISSUE TITLE
Function Call, validate_re(): input needs to be a String, not a NilClass at modules/dns/manifests/server/default.pp:29:3

### ISSUE THREAD

**Issue by ppouliot** [ajjahn/puppet-dns#190]
DNS Module Version 2.0.2
I get this error with both 3.8 and 4.x puppet versions.   by simply adding include dns::server to the node def.

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: Error while evaluating a Function Call, validate_re(): input needs to be a String, not a NilClass at /etc/puppetlabs/code/environments/production/modules/dns/manifests/server/default.pp:29:3 on node mother.openstack.tld","issue_kind":"RUNTIME_ERROR"}
/usr/share/ruby/vendor_ruby/puppet/indirector/rest.rb:207:in `is_http_200?'
/usr/share/ruby/vendor_ruby/puppet/indirector/rest.rb:100:in `find'
/usr/share/ruby/vendor_ruby/puppet/indirector/indirection.rb:201:in `find'
/usr/share/ruby/vendor_ruby/puppet/configurer.rb:294:in `block in retrieve_new_catalog'
/usr/share/ruby/vendor_ruby/puppet/util.rb:335:in `block in thinmark'
/usr/share/ruby/benchmark.rb:296:in `realtime'
/usr/share/ruby/vendor_ruby/puppet/util.rb:334:in `thinmark'
/usr/share/ruby/vendor_ruby/puppet/configurer.rb:293:in `retrieve_new_catalog'
/usr/share/ruby/vendor_ruby/puppet/configurer.rb:61:in `retrieve_catalog'
/usr/share/ruby/vendor_ruby/puppet/configurer.rb:106:in `prepare_and_retrieve_catalog'
/usr/share/ruby/vendor_ruby/puppet/configurer.rb:202:in `run_internal'
/usr/share/ruby/vendor_ruby/puppet/configurer.rb:134:in `block in run'
/usr/share/ruby/vendor_ruby/puppet/context.rb:64:in `override'
/usr/share/ruby/vendor_ruby/puppet.rb:246:in `override'
/usr/share/ruby/vendor_ruby/puppet/configurer.rb:133:in `run'
/usr/share/ruby/vendor_ruby/puppet/agent.rb:47:in `block (4 levels) in run'
/usr/share/ruby/vendor_ruby/puppet/agent/locker.rb:20:in `lock'
/usr/share/ruby/vendor_ruby/puppet/agent.rb:47:in `block (3 levels) in run'
/usr/share/ruby/vendor_ruby/puppet/agent.rb:117:in `with_client'
/usr/share/ruby/vendor_ruby/puppet/agent.rb:44:in `block (2 levels) in run'
/usr/share/ruby/vendor_ruby/puppet/agent.rb:82:in `run_in_fork'
/usr/share/ruby/vendor_ruby/puppet/agent.rb:43:in `block in run'
/usr/share/ruby/vendor_ruby/puppet/application.rb:179:in `call'
/usr/share/ruby/vendor_ruby/puppet/application.rb:179:in `controlled_run'
/usr/share/ruby/vendor_ruby/puppet/agent.rb:41:in `run'
/usr/share/ruby/vendor_ruby/puppet/application/agent.rb:361:in `onetime'
/usr/share/ruby/vendor_ruby/puppet/application/agent.rb:327:in `run_command'
/usr/share/ruby/vendor_ruby/puppet/application.rb:381:in `block (2 levels) in run'
/usr/share/ruby/vendor_ruby/puppet/application.rb:507:in `plugin_hook'
/usr/share/ruby/vendor_ruby/puppet/application.rb:381:in `block in run'
/usr/share/ruby/vendor_ruby/puppet/util.rb:496:in `exit_on_fail'
/usr/share/ruby/vendor_ruby/puppet/application.rb:381:in `run'
/usr/share/ruby/vendor_ruby/puppet/util/command_line.rb:146:in `run'
/usr/share/ruby/vendor_ruby/puppet/util/command_line.rb:92:in `execute'
/usr/bin/puppet:8:in `<main>'
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by ppouliot** [comment]
Sorry forgot to add, this is when running on Centos 7

**Comment by darkfoxprime** [comment]
This is caused by an updated made to `puppetlabs-stdlib` as of version `4.10.0`.  This has been fixed in the current dns module on github.  until it gets pushed to puppet forge, your work-around is to use a version of `puppetlabs-stdlib` that is older than `4.10.0`.

**Comment by ppouliot** [comment]
So should I pull from ajjahn::dns master?
p

**Comment by solarkennedy** [comment]
@ppouliot yes
